version: '3.9'

services:
  web:
    build: .
    container_name: google_login_django
    command: gunicorn google_login_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
