name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations & tests
        run: |
          python manage.py migrate
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t googlelogin-main-web .

      - name: Push Docker image (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag googlelogin-main-web yourdockerhubusername/googlelogin-main-web:latest
          docker push yourdockerhubusername/googlelogin-main-web:latest
